export const titles = [
  { id: "orbit-fall", title: "Orbit Fall", year: 2026, maturity: "13+", runtime: "2h 8m", match: 98, genre: "Sci-Fi", category: "Trending Now", rank: 1, color: ["#18334b", "#d49250"], description: "A lone cartographer discovers a signal beneath the storms of a forgotten world.", featured: true },
  { id: "silent-tide", title: "Silent Tide", year: 2025, maturity: "16+", runtime: "1h 54m", match: 96, genre: "Thriller", category: "Trending Now", rank: 2, color: ["#102b35", "#42a0a4"], description: "A marine biologist wakes to find her research vessel drifting—and the crew missing." },
  { id: "neon-district", title: "Neon District", year: 2026, maturity: "18+", runtime: "8 episodes", match: 95, genre: "Crime", category: "Trending Now", rank: 3, color: ["#32162f", "#d13b78"], description: "Two detectives chase a phantom through the sleepless heart of a future city." },
  { id: "the-last-summit", title: "The Last Summit", year: 2024, maturity: "13+", runtime: "2h 16m", match: 93, genre: "Adventure", category: "Trending Now", rank: 4, color: ["#172c36", "#d7c39b"], description: "Four climbers, one impossible peak, and a storm that changes every rule." },
  { id: "afterlight", title: "Afterlight", year: 2025, maturity: "16+", runtime: "10 episodes", match: 91, genre: "Drama", category: "Trending Now", rank: 5, color: ["#221d3d", "#8f74dc"], description: "Memories can be replayed. The truth is harder to find." },
  { id: "paper-kingdom", title: "Paper Kingdom", year: 2024, maturity: "7+", runtime: "1h 42m", match: 97, genre: "Family", category: "Critically Acclaimed", color: ["#57331f", "#e6a354"], description: "A fearless child folds a paper world into life to save her family." },
  { id: "north-star", title: "North Star", year: 2025, maturity: "13+", runtime: "6 episodes", match: 94, genre: "Documentary", category: "Critically Acclaimed", color: ["#0d3045", "#72b5d0"], description: "A breathtaking journey through the communities living at the edge of the Arctic." },
  { id: "borrowed-time", title: "Borrowed Time", year: 2023, maturity: "16+", runtime: "1h 49m", match: 92, genre: "Drama", category: "Critically Acclaimed", color: ["#3c241d", "#d1a076"], description: "An old watch gives a grieving musician one final day with the past." },
  { id: "wild-signal", title: "Wild Signal", year: 2025, maturity: "13+", runtime: "2h 2m", match: 90, genre: "Mystery", category: "New Releases", color: ["#17362b", "#8db66c"], description: "A radio host follows a strange broadcast deep into an uncharted forest." },
  { id: "redline", title: "Redline", year: 2026, maturity: "16+", runtime: "1h 57m", match: 89, genre: "Action", category: "New Releases", color: ["#3d1014", "#e3443f"], description: "A getaway driver has one night to outrun the city she once ruled." },
  { id: "small-hours", title: "Small Hours", year: 2025, maturity: "13+", runtime: "8 episodes", match: 88, genre: "Comedy", category: "New Releases", color: ["#2d2746", "#e9b972"], description: "Five night-shift strangers turn a quiet diner into their second home." },
  { id: "deep-blue", title: "Deep Blue", year: 2024, maturity: "7+", runtime: "4 episodes", match: 96, genre: "Nature", category: "Documentaries", color: ["#052d50", "#20a7c5"], description: "Descend into the least explored habitat on Earth." }
];

export const categories = [...new Set(titles.map((title) => title.category))];
